thoas/go-funk

README.rst

This is a great work and thank you!

update example of funk.Map at README.rst

---

README.rst

Fixed 1 spelling issue and made one sentence make a bit more sense when reading. Cool project btw,

Readme spelling and wording fix

---

.travis.yml

Also, we should probably activate Travis for PRs as well: https://stackoverflow.com/a/31882307/4237316.

Run Travis for Go 1.8 and 1.9

---

presence.go
presence_test.go

Resolves https://github.com/thoas/go-funk/issues/11.

Implement "Every" function

---

fill.go
fill_test.go

Resolves https://github.com/thoas/go-funk/issues/24.

Implement "Fill" function

---

operation.go
operation_test.go
reduce.go
reduce_test.go

Implement "Reduce" function

---

fill_test.go
zip_test.go

Just ran
gofmt -w .
on the project root. That's all. Helps with legibility.

all: gofmt

---

compact.go
compact_test.go

Implement funk.Compact

---

README.rst
benchmark_test.go
transform.go
transform_test.go
typesafe.go
typesafe_test.go

closes https://github.com/thoas/go-funk/issues/7
Hey @thoas!
Love the library. Wanted to get my hands dirty with something simple. Please let me know what needs to be changed!
Thanks

ISSUE-7: Implement funk.Drop

---

compact.go
reduce.go

Also modified Compact to be able to take an array (in addition to slices).

Add missing documentation for Compact/Reduce

---

.travis.yml

might want to drop 1.7 too but didn't before getting confirm.

travis: add go1.10

---

builder.go
builder_test.go
chain_builder.go
chain_builder_test.go
lazy_builder.go
lazy_builder_test.go

Implement Builder mecanism

---

.gitignore
helpers.go
helpers_test.go

1. add an item .idea in .gitignore
2. add nil check for funk.IsIteratee
3. add an unit test for 2

Add nil check for funk.IsIteratee

---

example_presence_test.go
go.mod
go.sum
presence.go
presence_test.go

@thoas  This PR should resolve #10  . I have added examples as well so that it gets reflected in the godocs as well. Also I am new to Golang so any feedback would be appreciated.

Implement funk some

---

presence.go
presence_test.go

And now `Find` support map.
Example is in the test.
https://github.com/WingGao/go-funk/blob/28a13aabee572a14a5667ed9d467cc353fccac8a/presence_test.go#L153-L168

feat: add `FindKey` to find the elemet and key in a collection

---

min.go
min_test.go

Hello! I made a Min method similar to Max.

Implement Min method

---

README.rst

I hope these little corrections are helpful.

Fixed some typos and grammar in README

---

README.rst
retrieve.go
retrieve_test.go

Similar to the Scala function.
```golang
str := "hello world"
funk.GetOrElse(&str, "foobar")   // string{"hello world"}
funk.GetOrElse(str, "foobar")    // string{"hello world"}
funk.GetOrElse(nil, "foobar")    // string{"foobar"}
```

Adding GetOrElse

---

builder.go
chain_builder.go
lazy_builder.go
without.go
without_test.go

feat: implement Without

---

transform.go

Added explanation

---

typesafe.go
typesafe_test.go

Resolves issue: https://github.com/thoas/go-funk/issues/93

Add uint, uint32 and uint64 support to typesafe.go

---

predicate.go
predicate_test.go

the methods should allow a user to run several predicates on a given value

Add predicate methods

---

README.rst
chain_builder_test.go
helpers.go
helpers_test.go
lazy_builder_test.go
predicate.go
presence.go
presence_test.go
utils.go

PR for the feature request #109

Add possibility to use predicate for `Contains`, `IndexOf` & `LastIndexOf` functions

---

README.rst
funk_test.go
retrieve.go
retrieve_test.go

```go
m := map[string]interface{}{
"bar": map[string]interface{}{
"name": "foobar",
},
}
Get(m, "bar.name")
// returns "foobar"
```
Also, can you publish a new release @thoas ? 🙏

Get: retrieves the value of a path of *map*

---

retrieve.go
retrieve_test.go
utils.go

Fixes #106

---

README.rst
builder.go
chain_builder.go
chain_builder_test.go
lazy_builder.go
lazy_builder_test.go
reduce.go
reduce_test.go

Fixes issue #50

---

typesafe.go
typesafe_test.go

Typesafe 'FilterBool', 'ContainsBool', 'ReverseBools', 'IndexOfBool', 'LastIndexOfBool', 'UniqBool', 'ShuffleBool', and 'DropBool' added.

Add typesafe bool functions

---

transform.go

Hi, I found unnecessary increment in Uniq func.

remove unnecessary increment in Uniq

---

README.rst
transform.go
transform_test.go

Hello, I add a new transform function `ToSet()`, which I frequently use in my daily coding.

feat: add ToSet()

---

funk_test.go
retrieve.go
retrieve_test.go

Thank you for this funky library 🎸 
~~Draft~~ PR in an attempt to fix https://github.com/thoas/go-funk/issues/158

fix: Don't panic on nil embedded structs
