thoas/go-funk

presence.go
Improvements:
- Use `switch` to only call `Kind()` once.
- Remove the case where `inValue` is a map that does not contain the key, in which case the execution just continues. It would still return the correct value, but it was inefficient.
- Use `range` for the Map scenario. Because why not?
=> In 'Contains', save one comparison against reflect.Slice for Map that does not contain the key

zip.go, zip_test.go
Resolves https://github.com/thoas/go-funk/issues/1.
Zip is one of my favorite functions in Python, so I thought I would contribute a bit by implementing it in Go as well.
Added tests for arrays and slices. For handling native types, as well as structs.
=> Implementing "Zip" function

transform.go
We won't really deal with functions that return more than two
parameters. Instead of failing silently, we'd better warn it earlier.
=> Panic if the map function doesn't return one or two parameters.

scan_test.go
This is fixing a problem in 'TestForEachRight' that appears because it incorrectly relies on the underlying implementation of Map in Golang
The ordering is not guaranteed, but rather the slice output format is randomized strictly to disallow reliying on it. This happens at least for all Goversions >=1.7.
Check that numbers are in the output without asserting the order.
This is also the reason why unit tests on master fail every now and then, and made worse by running tests on 1.8 and 1.9!
Provoke the problem by running the test quite repeatedly until it fails:
(set -e && for i in {1..100}; do go test; done)
=> Fixing a problem in 'TestForEachRight' that appears because it incorrectly relies on the underlying implementation of Map in Golang

helpers.go
I believe it's better to avoid seeding the global rand source here.
=> Remove rand.Seed from RandomInt

typesafe.go, typesafe_test.go
There are int, **int32**, int64 in Go.
Why not support int32? 😄
=> Support xxxInt32 operations

presence.go, presence_test.go
As of now, `Contains()` will return `false` if called on an array (i.e. a fixed length slice). This PR fixes the issue.
=> Support Contains() for arrays too

presence.go, presence_test.go
Hi,
I changed function `Contains` to throw a panic when the type is not supported by the function. 
I had a case where in my project when using `Contains` with an unsupported type was not signaled and it took me some time to find it out :neckbeard: 
For the test case I just check if an unsupported type throws a panic.
=> Contains will panic on unsupported types instead of returning false

retrieve.go
fix the bug ：reflect: call of reflect.Value.Type on zero Value
if the slice is nil， or len==0， will be panic.
the case:
```
type Foo struct{
Bar[]int
}
func TestGoFunk(t *testing.T) {
foo := []Foo{}
bars := funk.Get(foo, "Bar") //panic !!
fmt.Print(bars)
}
```
=> fix the bug reflect on zero Value

typesafe.go
Thanks for the library.
When the expected return value of LastIndexOf... should be 0, -1 is returned. This PR fixes an iteration in lastIndexOf, thereby fixing the bug.
=> fix bug in lastIndexOf

README.rst, intersection.go, intersection_test.go
Returns the difference between two collections.
```golang
left, right := funk.Difference([]int{1, 2, 3, 4}, []int{2, 4, 6})  // []int{1, 3}, []int{6}
left, right := funk.Difference([]string{"foo", "bar", "hello", "bar"}, []string{"foo", "bar"})  // []string{"hello"}, []string{}
```
Solving #13
=> Add support for funk.Difference

README.rst, benchmark_test.go, subtraction.go, subtraction_test.go
Subtract tests were sometimes crashing, because of random output.
Subtract function is now 5-10% slower.
=> Subtract: Preserve order and duplication

benchmark_test.go, builder.go, chain_builder.go, go.sum, intersection.go, intersection_test.go, join.go, join_primitives.go, join_test.go, lazy_builder.go
`Join` method implements methods to combine two collections:
- It accepts all generic collection (using reflect package)
- It also accepts primitive collection ([]int, []int32, []int64, []float32, []float64, []string) through dedicated join methods
- Several join types are available:
- Inner join
- Outer join
- Left join (exclusive)
- Right join (exclusive)
- It can be chained through builders
`Join` method is used as following: `Join(CollectionA, CollectionB, Type)`. For example, a left join between two string arrays is written `Join([]string{"a","b","c"}, []string{"c","d","e"}, LeftJoin)`
**NB:** `InnerJoin` is similar to `Intersect` (a bit heavier due to deduplication check). But, because the result is not always the same (see new Intersect test), I didn't rewrote it (in order to avoid …
=> Implement Join methods for "generic" and some primitives

transform.go
funk.Map requires two arguments, not one
=> Fix error message

subtraction.go, subtraction_test.go
SubtactingString had a bug where calling
```
SubtractString([]string{"bar", "bar"}, []string{})
```
would return empty array
=> Subtacting with empty array should return the first

README.rst, assign.go, assign_test.go, funk_test.go, map_test.go
funk.Set(in,val,path) Traverse "in" with path, and set the end path variable to val.
- Implemented Set() as the counter part of funk.Get().
- Resolves array in the same way as Get().
- Handles interface{} along the path.
- Added many tests.
- Changed Foo with one more field GeneralInterface to hold arbitrary value for testing.
Will change README if pull request is approved.
=> Feature: Set Struct Field Based On Path

retrieve.go, retrieve_test.go
fix nil check in GetOrElse.
Added handling of this case:
`is.False(interface{}((*string)(nil)) == nil)`
=> fix nil check in GetOrElse

README.rst
Documentation of funk.Prune does not show up. This is the fix.
=> Fix readme prune

README.rst, builder.go, chain_builder.go, chain_builder_test.go, lazy_builder.go, lazy_builder_test.go, transform.go, transform_test.go
I found an urge to use a `FlatMap` operation that was missing from the library.
=> Add `FlatMap` and `Flatten` transformation operations

funk_test.go, map_test.go, retrieve.go, retrieve_test.go
Add a GetAllowZero function to retrievers 
Some struct values such as boolean false will return as nil if we use the normal Get function. 
`
foo := struct {
X bool
}{false}
funk.Get(foo, "X")  // -> nil, although it was set on purpose to false
funkGetAllowZero(foo, "X") // -> false
`
The same is true for empty strings, integer with the value 0 etc'.
Also in case if the type is a pointer and is Zero it will return nil, like normal get.
I fixed tests + added a few more, if PR is approved, ill add documentation/tests as required.
=> Feature: allow retrieve with zero values

join.go, join_test.go
Join array of interfaces which implement the function `String() string`. This resolves Issue [#121](https://github.com/thoas/go-funk/issues/121).
=> Add StringerJoin()

README.rst, transform.go, transform_test.go
This PR:
- `ToMap()` is currently only for slices. This PR adds support to arrays.
- Panic when `pivot` is not a field of the struct.
Before this PR, the panic message was ambiguous:
```
panic: interface conversion: reflect.Type is nil, not *reflect.rtype [recovered]
panic: interface conversion: reflect.Type is nil, not *reflect.rtype
```
Now:
```
panic: `Id` must be a field of the struct Foo [recovered]
panic: `Id` must be a field of the struct Foo
```
=> feat: support ToMap for arrays too

union.go, union_test.go
Not sure exactly where Union with slices would be preferable to just builtin `append()`, but added it for completeness when wanting a Union for maps. Also added a typesafe helper for the common case of string maps.
=> feat: Add `Union` method and typesafe `UnionStringMap`

README.rst, transform.go, transform_test.go
Pretty useful for matching by a struct attribute.
Usage:
```go
funk.UniqBy([]int{0, 1, 1, 2, 3, 0, 0, 12}, func(nbr int) int {
return nbr % 3
}) // []int{0, 1, 2}
foo1 := Foo{
ID: 42,
FirstName: "Bob",
}
foo2 := Foo{
ID: 42,
FirstName: "Bob",
}
funk.UniqBy([]Foo{foo1, foo2}, func(f Foo) int {
return f.ID
}) // []Foo{ Foo{ID: 42, Firstname: "Bob"} }
```
A new release would be appreciated. 🙏
=> Adding _.uniqBy() function

.github/workflows/golangci-lint.yml, retrieve_test.go
https://github.com/thoas/go-funk/pull/159 fails due to a lint error unrelated to that PR. This PR fixes the lint error
=> chore: Fix lint error

funk_test.go, retrieve.go, retrieve_test.go
Sorry for the trouble but I've noticed this in our CI tests after updating to `go-funk` version with my fix.
This is a follow up to https://github.com/thoas/go-funk/pull/159
We should only consider pointer to structs when looking at embedded structs, as non pointers can never be `nil`.
The previous code would panic on structs since I used `IsNil` which can only called on pointers to structs.
This fixes the issue and adds a test to catch the previous panic
=> fix: Only consider pointer to structs when checking for embedded fields

README.rst, retrieve.go, retrieve_test.go
=> Adds funk.Get support for complex map keys

typesafe.go
add implementation of ChunkUInts, ChunkUInt32s, ChunkUInt64s.
it seems that using Generic in go 1.18 would be a better choice.
=> add implementation of ChunkUInts, ChunkUInt32s, ChunkUInt64s

README.rst, scan.go, scan_test.go
Maybe ForEach can modify elements is a good idea, I don't know. But some real scene need this feature.
Someone prefers
`results := []int{}`
`funk.ForEach([]int{1,2,3}, func(x int){ results = append(results, x * 2})` 
`resultsAnother := []int{}`
`funk.ForEach(results, func(x int){ resultsAnother = append(resultsAnother, x * 3})` 
but someone prefers
`data := []int{1,2,3}`
`funk.ForEach(data, func(x *int){ *x = *x * 2})`
`funk.ForEach(data, func(x *int){ *x = *x * 3})`
go's map cannot be modified by the reflect value. reflect#Value#MapIndex#CanSet is false. Use SetMapIndex is a way, but it need a `func(x *any) any` as predicate func  breaks go-funk's consensual, so I left it.
=> ForEach slice modify(optional)

README.rst
after testing, the result of `funk.LastIndexOf([]string{"foo", "bar"}, func(value string) bool {
return value == "bar"
})` is 1, and I gusse that this sample code may missed a "bar"
=> fix: Update LastIndexOf sample code in README.rst 
